#!/bin/bash
# generate-indexes.sh — Regenerates framework-library-index.md and modes-index.md
# Run during maintenance cycle or after adding/modifying frameworks or modes.

set -uo pipefail

# Resolve the workspace the way start.sh and run-ora-server.sh do: an explicit
# ORA_HOME wins, otherwise this script belongs to the checkout it lives in. The
# old "${HOME}/ora" pin meant a clone anywhere else read and rewrote a
# completely unrelated tree — or nothing at all, on a machine with no ~/ora.
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
ORA_DIR="${ORA_HOME:-$(cd -- "${SCRIPT_DIR}/.." && pwd -P)}"
if [ ! -d "$ORA_DIR" ]; then
    echo "ERROR: ORA_HOME is not a directory: $ORA_DIR" >&2
    exit 1
fi
ORA_DIR="$(cd -- "$ORA_DIR" && pwd -P)"
CONFIG_DIR="${ORA_DIR}/config"

# --- Framework Library Index ---
FRAMEWORK_INDEX="${CONFIG_DIR}/framework-library-index.md"
echo "# Framework Library Index" > "$FRAMEWORK_INDEX"
echo "" >> "$FRAMEWORK_INDEX"
echo "*Auto-generated by generate-indexes.sh — do not edit manually.*" >> "$FRAMEWORK_INDEX"
echo "" >> "$FRAMEWORK_INDEX"
echo "| File | Path (relative to the Ora workspace root) | Description |" >> "$FRAMEWORK_INDEX"
echo "|---|---|---|" >> "$FRAMEWORK_INDEX"

for dir in "${ORA_DIR}/frameworks/book" "${ORA_DIR}/frameworks/user" "${ORA_DIR}/frameworks/personal"; do
    if [ -d "$dir" ]; then
        for f in "$dir"/*.md; do
            [ -f "$f" ] || continue
            filename=$(basename "$f")
            # Workspace-relative, never absolute: this table is read into a
            # model's context window and ships to every clone, so the
            # packager's own home directory in it is both wrong and useless
            # to the reader.
            relpath="${f#"${ORA_DIR}"/}"
            # Extract first non-empty, non-heading, non-frontmatter line as description
            desc=$(awk '/^---$/{fm++; next} fm==1{next} /^#/{next} /^$/{next} {print; exit}' "$f" | head -c 120)
            echo "| ${filename} | ${relpath} | ${desc} |" >> "$FRAMEWORK_INDEX"
        done
    fi
done

echo "Generated: ${FRAMEWORK_INDEX}"

# --- Modes Directory Index ---
python3 - "$ORA_DIR" <<'PY' || exit 1
from pathlib import Path
import os
import sys
import tempfile

root = Path(sys.argv[1]).resolve()
sys.path.insert(0, str(root))
from orchestrator.routing_sources import compile_routing_sources, render_routing_views

body = render_routing_views(compile_routing_sources(root))["config/modes-index.md"]
target = root / "config" / "modes-index.md"
temporary = None
try:
    with tempfile.NamedTemporaryFile("w", encoding="utf-8", dir=target.parent,
                                     prefix=".modes-index-", delete=False) as output:
        temporary = Path(output.name)
        output.write(body)
    os.replace(temporary, target)
finally:
    if temporary is not None and temporary.exists():
        temporary.unlink()
print(f"Generated: {target}")
PY
